name: improved-couscous-tests
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements.dev.txt
    - name: Check styles with Black
      run: black --check *.py hello
    - name: Check imports with isort
      run: isort --check *.py hello
    - name: Test with pytest
      run: pytest
